apiVersion: v1
kind: ConfigMap
metadata:
  name: new-event-config
  namespace: new-event
data:
  EVENT_SERVICE_URL: "http://event-service:5000"
  PROGRAM_SERVICE_URL: "http://program-service:5001"
  ANALYTICS_SERVICE_URL: "http://analytics-service:5003"
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_DATABASE: "new_event_analytics"
